### ISSUE TITLE
Not published on npmjs

### ISSUE THREAD

**Issue by IgnusG** [mdluo/babel-plugin-directory-named-module#1]
I can't find the plugin on npmjs. The link in the readme is dead as well?

**Comment by mdluo** [comment]
Ref: https://github.com/shaketbaby/directory-named-webpack-plugin/issues/9#issuecomment-292410982

**Comment by gkiely** [comment]
I wasn't able to get this working with git, it would be great if it could go back up on npm :)

**Comment by capsudo** [comment]
I could not install it from git with following command `npm install https://github.com/mdluo/babel-plugin-directory-named-module.git` but I got it working after building it and `npm install https://github.com/monkeydri/babel-plugin-directory-named-module/tarball/build`.

*Note : I am not installing it as a devDependency since I am using CRA.*
